/**
 * route.yml emission - porting-plan Unit 17, task item (d) (ENG-02 routing).
 *
 * Ported from legacy IS/pack-builder.ts 2436-2503. Each log type gets a PAIR of
 * routes:
 *   1. a REDUCTION route (final:true, enabled) whose pipeline is the
 *      self-contained reduction pipeline (extract + reduce + transform); emitted
 *      only when the table has reduction rules;
 *   2. a PASSTHROUGH route (final:true) whose pipeline is the transform-only
 *      pipeline; disabled when a reduction route exists, enabled otherwise.
 * The disable-swap is the documented operational lever: to skip reduction,
 * disable the reduction route and enable the passthrough route (comment preserved
 * verbatim).
 *
 * FILTER KEY CONTRACT (section 3 item 7): routes use `filter:`, NEVER
 * `condition:`. The regression that once asserted this against a string literal
 * is re-pointed at THIS emitter (route-yml.test.ts), and the emitted route.yml
 * passes checkCriblYaml.
 *
 * NAMING: every id here is derived from the SINGLE {@link TablePlan.suffix} via
 * the naming helpers, so a route's `pipeline:` target can never diverge from the
 * pipeline dir (the legacy suffix-mismatch defect, fixed + pinned).
 *
 * OVERFLOW/PER-LOGTYPE COLLISION (conscious resolution): the legacy scaffold
 * keyed overflow config (and format, and fields) by `table.sentinelTable` in a
 * shared Map. For a multi-logType single table (Cloudflare HTTP/WAF/DNS all
 * targeting CloudflareV2_CL) the last logType overwrote the others. The plan
 * model resolves this by making each TablePlan a per-logType entry that carries
 * its OWN overflow/format/fields; route.yml therefore emits one route pair PER
 * logType, all pointing at the SAME destination for the shared table. Pinned by
 * plan.test.ts / route-yml.test.ts.
 *
 * Pure: no IO, no fetch, no React, no Date/crypto/Math.random.
 */

import type { PipelinePlan, TablePlan } from "./models";
import {
  passthroughRouteId,
  reductionRouteId,
} from "./naming";

/** Build the route filter line: unquoted-match-all vs an escaped condition. */
function filterLine(routeCondition: string): string {
  // YAML `filter: true` (unquoted) means match all; we always quote the value.
  return routeCondition === "true"
    ? '    filter: "true"'
    : `    filter: "${routeCondition.replace(/"/g, '\\"')}"`;
}

/** Emit the route entry pair for one resolved {@link TablePlan}. */
export function buildRouteEntries(
  plan: PipelinePlan,
  table: TablePlan,
): string[] {
  const entries: string[] = [];
  const hasRules = table.reductionRules !== null;
  const line = filterLine(table.routeCondition);

  // Reduction route: full pipeline with volume reduction enabled
  if (hasRules) {
    entries.push(
      [
        `  - id: ${reductionRouteId(plan.vendorPrefix, table.suffix)}`,
        `    name: "Reduction + Transform: ${table.suffix}"`,
        `    pipeline: ${table.reductionPipelineId}`,
        line,
        `    output: ${table.destinationId}`,
        "    final: true",
        "    disabled: false",
        `    description: Reduction + Transform for ${table.suffix} events`,
      ].join("\n"),
    );
  }

  // Passthrough route: transformation only. Disabled when a reduction route
  // exists, enabled when it does not.
  entries.push(
    [
      `  - id: ${passthroughRouteId(plan.vendorPrefix, table.suffix)}`,
      `    name: "Transform: ${table.suffix}"`,
      `    pipeline: ${table.pipelineName}`,
      line,
      `    output: ${table.destinationId}`,
      "    final: true",
      `    disabled: ${hasRules ? "true" : "false"}`,
      `    description: Transform only for ${table.suffix} events`,
    ].join("\n"),
  );

  return entries;
}

/** Emit the full route.yml for a resolved {@link PipelinePlan}. */
export function generateRouteYml(plan: PipelinePlan): string {
  // Match-all pairs go LAST (live flaw 2026-07-13: a final match-all route
  // emitted first made every later route unreachable). Discriminated pairs
  // keep their relative order; at most one match-all is reachable, so any
  // beyond the first get an honest warning comment.
  const ordered = [...plan.tables].sort(
    (a, b) =>
      Number(a.routeCondition === "true") - Number(b.routeCondition === "true"),
  );
  const catchAlls = ordered.filter((t) => t.routeCondition === "true").length;
  const allRouteEntries: string[] = [];
  for (const table of ordered) {
    allRouteEntries.push(...buildRouteEntries(plan, table));
  }

  return [
    `# Routes for ${plan.solutionName}`,
    "# Generated by Cribl SOC Optimization Toolkit",
    "#",
    "# Each log type has two routes:",
    "#   1. Reduction + Transform (enabled): full pipeline with volume reduction",
    "#   2. Transform only (disabled): same pipeline without reduction",
    "# To skip reduction: disable the reduction route and enable the passthrough route.",
    ...(catchAlls > 1
      ? [
          "#",
          `# WARNING: ${catchAlls} log types have no distinguishing fields - their`,
          "# match-all routes overlap and only the first receives events. Edit the",
          "# filters below to separate them.",
        ]
      : []),
    "",
    "id: default",
    "groups: {}",
    "routes:",
    ...allRouteEntries,
    "",
  ].join("\n");
}
