/**
 * Shipped Logs-Ingestion-fit lookup (2026-07-15): the precomputed
 * solution -> tier map generated by scripts/generate-ingestion-classification
 * .mjs (which runs the same {@link classifyConnectorIngestion} logic over the
 * Azure-Sentinel repo). Lets the solution browser tag EVERY row instantly
 * without decoding 400+ solutions' connectors at runtime - the lazy per-
 * solution decode still computes the tier LIVE on selection (authoritative,
 * overrides any stale shipped entry).
 *
 * Pure: no IO. The JSON asset is bundled at build time (the same pattern as
 * the other generated assets in ../../assets).
 */

import classification from "../../assets/sentinel-ingestion-classification.json";
import type { IngestionTier } from "./ingestion-class";

/** One solution's shipped classification (tier + the CCF kind, if any). */
export interface SolutionIngestion {
  tier: IngestionTier;
  /** The CCF connector kind that drove the tier (e.g. "Push"), or "". */
  kind: string;
}

interface ClassificationFile {
  meta: unknown;
  solutions: Record<string, SolutionIngestion>;
}

const SOLUTIONS: Record<string, SolutionIngestion> =
  (classification as ClassificationFile).solutions;

function norm(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, "");
}

// Normalized-name index for a resilient fallback (the browser passes the repo
// folder name, which matches exactly; normalization catches punctuation drift).
const BY_NORM = new Map<string, SolutionIngestion>();
for (const [name, cls] of Object.entries(SOLUTIONS)) {
  const key = norm(name);
  if (!BY_NORM.has(key)) BY_NORM.set(key, cls);
}

/**
 * The shipped tier for a solution by name (exact match first, then a
 * normalized-name fallback). Returns null when the solution is not in the
 * generated map (a brand-new solution, or one with no connector) - the caller
 * shows no tag and relies on the live per-solution classification instead.
 */
export function lookupSolutionIngestion(solutionName: string): SolutionIngestion | null {
  const exact = SOLUTIONS[solutionName];
  if (exact !== undefined) return exact;
  return BY_NORM.get(norm(solutionName)) ?? null;
}

/** A one-line rationale for a tier (+ kind), for the browser tooltip. */
export function ingestionTierReason(tier: IngestionTier, kind: string): string {
  switch (tier) {
    case "recommended":
      return (
        "CCF Push connector - the Azure Logs Ingestion API is its native " +
        "ingress, so Cribl delivers directly to it."
      );
    case "supported":
      return kind !== ""
        ? `CCF ${kind} connector - Cribl can deliver into its table via the ` +
            "Logs Ingestion API (leave the native connector off to avoid duplicates)."
        : "Declares a custom table / DCR - Cribl can push into it via the Logs " +
            "Ingestion API.";
    case "legacy":
      return (
        "Agent, Azure Functions, or name-only connector - not a native Logs " +
        "Ingestion API target."
      );
  }
}
