export {
  buildDcrColumnSet,
  buildStreamDeclaration,
  ensureCustomTableSuffix,
  isKnownColumnType,
  mapColumnType,
  normalizeCustomSchemaColumns,
  selectSchemaColumns,
  stripReservedTableCreationColumns,
  SchemaMappingError,
  CUSTOM_SYSTEM_COLUMNS,
  DCR_COLUMN_TYPES,
  DEFAULT_TRANSFORM_KQL,
  GUID_LIKE_TYPES,
  LOG_ANALYTICS_DESTINATION_NAME,
  NATIVE_SYSTEM_COLUMNS,
  RESERVED_TABLE_CREATION_COLUMNS,
} from "./schema-mapping";
export type {
  CustomSchemaFileColumn,
  CustomTableColumn,
  DcrColumn,
  DcrColumnSetResult,
  DcrColumnType,
  DcrDataFlow,
  DcrStreamDeclaration,
  DropReason,
  DroppedColumn,
  LogAnalyticsColumn,
  TableMode,
  TableSchemaColumnSources,
  UnknownTypeColumn,
} from "./schema-mapping";
