// Change Detection Module
// Tracks the state of vendor schemas and Sentinel Content Hub when packs are
// built, then detects changes on subsequent app loads. Provides visual alerts
// in the GUI so users know which solutions have upstream changes.
//
// Two data stores:
//   1. Build Snapshots -- captured when a pack is scaffolded, records the exact
//      schema state (file SHAs, field fingerprints) at build time
//   2. Change Alerts -- generated by comparing current GitHub state against
//      snapshots, categorized by severity and change type

import { IpcMain, BrowserWindow } from 'electron';
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { githubGet, rawGet, SENTINEL_REPO, GitHubContent } from './github';
import { loadGitHubPat } from './auth';
import { lookupDynamicEntry } from './registry-sync';
import {
  isRepoReady, getSolutionsDir, listConnectorFiles,
  readConnectorJson, getFileHash, readRepoFile,
  listSolutionFiles,
} from './sentinel-repo';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SchemaFingerprint {
  logTypeId: string;
  logTypeName: string;
  fieldCount: number;
  fieldHash: string;  // SHA256 of sorted field names+types
}

export interface ConnectorFileSnapshot {
  fileName: string;
  filePath: string;
  sha: string;
  size: number;
}

export interface AnalyticRuleSnapshot {
  fileName: string;
  sha: string;
  ruleName: string;
  severity: string;
  fieldCount: number;
}

export interface BuildSnapshot {
  packName: string;
  solutionName: string;
  buildTime: number;
  solutionPath: string;  // Relative path (e.g., "Solutions/Cloudflare")
  gitCommit: string;     // Git commit hash of local repo at build time
  connectorFiles: ConnectorFileSnapshot[];
  schemaFingerprints: SchemaFingerprint[];
  analyticRules?: AnalyticRuleSnapshot[];  // Snapshot of analytics rules at build time
  totalFields: number;
}

export interface GitCommitInfo {
  hash: string;
  date: string;
  subject: string;
  author: string;
}

export interface FileDiff {
  file: string;
  status: 'added' | 'modified' | 'deleted' | 'renamed';
  additions: number;
  deletions: number;
}

export type ChangeSeverity = 'info' | 'warning' | 'critical';
export type ChangeCategory =
  | 'new_connector'       // New Data Connector file added
  | 'modified_connector'  // Existing connector file changed (SHA mismatch)
  | 'removed_connector'   // Connector file removed
  | 'new_log_type'        // New table/log type added
  | 'removed_log_type'    // Table/log type removed
  | 'schema_change'       // Field definitions changed in existing log type
  | 'field_count_change'  // Number of fields changed
  | 'new_analytic_rule'   // New analytics rule added to solution
  | 'modified_analytic_rule' // Existing analytics rule changed
  | 'removed_analytic_rule'; // Analytics rule removed from solution

export interface ChangeDetail {
  category: ChangeCategory;
  severity: ChangeSeverity;
  description: string;
  // Specifics for each category
  fileName?: string;
  logTypeName?: string;
  oldValue?: string | number;
  newValue?: string | number;
}

export interface ChangeAlert {
  packName: string;
  solutionName: string;
  solutionPath: string;
  buildTime: number;
  checkTime: number;
  hasChanges: boolean;
  changes: ChangeDetail[];
  // Summary counts
  totalChanges: number;
  criticalCount: number;
  warningCount: number;
  infoCount: number;
}

interface ChangeDetectionState {
  status: 'idle' | 'checking' | 'done' | 'error';
  alerts: ChangeAlert[];
  lastCheckTime: number;
  errorMessage: string;
}

// ---------------------------------------------------------------------------
// Storage
// ---------------------------------------------------------------------------

function getDataDir(): string {
  const appData = process.env.APPDATA || process.env.HOME || '';
  const dir = path.join(appData, '.cribl-microsoft', 'change-detection');
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return dir;
}

function getSnapshotsPath(): string {
  return path.join(getDataDir(), 'snapshots.json');
}

function getAlertsPath(): string {
  return path.join(getDataDir(), 'alerts.json');
}

function readSnapshots(): Record<string, BuildSnapshot> {
  const p = getSnapshotsPath();
  if (fs.existsSync(p)) {
    try { return JSON.parse(fs.readFileSync(p, 'utf-8')); } catch { /* corrupt */ }
  }
  return {};
}

function writeSnapshots(snapshots: Record<string, BuildSnapshot>): void {
  try { fs.writeFileSync(getSnapshotsPath(), JSON.stringify(snapshots, null, 2)); } catch { /* non-fatal */ }
}

function readAlerts(): ChangeAlert[] {
  const p = getAlertsPath();
  if (fs.existsSync(p)) {
    try { return JSON.parse(fs.readFileSync(p, 'utf-8')); } catch { /* corrupt */ }
  }
  return [];
}

function writeAlerts(alerts: ChangeAlert[]): void {
  try { fs.writeFileSync(getAlertsPath(), JSON.stringify(alerts, null, 2)); } catch { /* non-fatal */ }
}

// ---------------------------------------------------------------------------
// GitHub API Helpers (replace local git commands -- works with API-fetched repo)
// ---------------------------------------------------------------------------

const GITHUB_API_BASE = 'https://api.github.com/repos/Azure/Azure-Sentinel';

function getGitHubAuthHeader(): Record<string, string> {
  const pat = loadGitHubPat();
  if (pat) return { 'Authorization': `Bearer ${pat}` };
  return {};
}

async function ghFetch<T = unknown>(url: string): Promise<T | null> {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { net } = require('electron');
    const resp = await net.fetch(url, {
      headers: {
        'Accept': 'application/vnd.github+json',
        'User-Agent': 'Cribl-Microsoft-Integration',
        ...getGitHubAuthHeader(),
      },
    });
    if (!resp.ok) return null;
    return await resp.json() as T;
  } catch { return null; }
}

// Get the current HEAD commit SHA of the master branch
async function getCurrentCommit(): Promise<string> {
  const data = await ghFetch<{ object?: { sha?: string } }>(
    `${GITHUB_API_BASE}/git/ref/heads/master`,
  );
  return data?.object?.sha?.slice(0, 12) || '';
}

// Get commit history for a specific path since a given commit.
// Uses GitHub's Commits API with the path query parameter.
export async function getGitLogForPath(
  relativePath: string,
  sinceCommit?: string,
  maxEntries: number = 20,
): Promise<GitCommitInfo[]> {
  // Normalize path for URL (encode spaces etc.)
  const encodedPath = encodeURIComponent(relativePath).replace(/%2F/g, '/');
  let url = `${GITHUB_API_BASE}/commits?path=${encodedPath}&per_page=${maxEntries}`;

  // If sinceCommit is provided, first resolve its date (GitHub's "since" param takes ISO date, not SHA)
  if (sinceCommit) {
    const baseCommit = await ghFetch<{ commit?: { author?: { date?: string } } }>(
      `${GITHUB_API_BASE}/commits/${sinceCommit}`,
    );
    const sinceDate = baseCommit?.commit?.author?.date;
    if (sinceDate) {
      url += `&since=${encodeURIComponent(sinceDate)}`;
    }
  }

  const commits = await ghFetch<Array<{
    sha: string;
    commit: { author: { name: string; date: string }; message: string };
  }>>(url);
  if (!commits) return [];

  return commits.map((c) => ({
    hash: c.sha.slice(0, 12),
    date: c.commit.author.date,
    subject: c.commit.message.split('\n')[0],
    author: c.commit.author.name,
  }));
}

// Get file-level diff between a commit and HEAD for a path.
// Uses GitHub's Compare API (/compare/{base}...{head}) which returns all changed files
// with additions/deletions counts -- equivalent to `git diff --numstat --name-status`.
export async function getFileDiffSinceCommit(
  relativePath: string,
  sinceCommit: string,
): Promise<FileDiff[]> {
  // Normalize path prefix for filtering (API returns all changes; we filter client-side)
  const pathPrefix = relativePath.endsWith('/') ? relativePath : relativePath + '/';

  const data = await ghFetch<{
    files?: Array<{
      filename: string;
      status: string;
      additions: number;
      deletions: number;
    }>;
  }>(`${GITHUB_API_BASE}/compare/${sinceCommit}...master`);

  if (!data?.files) return [];

  const diffs: FileDiff[] = [];
  for (const f of data.files) {
    // Filter to files within the requested path
    if (!f.filename.startsWith(pathPrefix) && f.filename !== relativePath) continue;

    let status: FileDiff['status'] = 'modified';
    if (f.status === 'added') status = 'added';
    else if (f.status === 'removed') status = 'deleted';
    else if (f.status === 'renamed') status = 'renamed';

    diffs.push({
      file: f.filename,
      status,
      additions: f.additions || 0,
      deletions: f.deletions || 0,
    });
  }

  return diffs;
}

// ---------------------------------------------------------------------------
// Snapshot Creation
// ---------------------------------------------------------------------------

function hashFields(fields: Array<{ name: string; type: string }>): string {
  const sorted = [...fields].sort((a, b) => a.name.localeCompare(b.name));
  const str = sorted.map((f) => `${f.name}:${f.type}`).join('|');
  return crypto.createHash('sha256').update(str).digest('hex').slice(0, 16);
}

// Capture a build snapshot using the local repo clone.
// Records git commit hash, file content hashes, and schema fingerprints.
export async function captureSnapshot(
  packName: string,
  solutionName: string,
  logTypes: Array<{ id: string; name: string; fields: Array<{ name: string; type: string }> }>,
): Promise<BuildSnapshot> {
  const solutionPath = await findSolutionPath(solutionName);
  const connectorFiles: ConnectorFileSnapshot[] = [];
  const gitCommit = await getCurrentCommit();

  if (solutionPath && isRepoReady()) {
    // Read connector files from local clone
    const solName = solutionPath.replace(/^Solutions\//, '');
    const files = listConnectorFiles(solName);
    for (const file of files) {
      connectorFiles.push({
        fileName: file.name,
        filePath: file.path,
        sha: getFileHash(file.path),
        size: file.size,
      });
    }
  } else if (solutionPath) {
    // Fallback to GitHub API
    try {
      const files = await fetchConnectorFiles(solutionPath);
      for (const file of files) {
        connectorFiles.push({
          fileName: file.name,
          filePath: file.path,
          sha: file.sha || '',
          size: file.size || 0,
        });
      }
    } catch { /* skip */ }
  }

  const schemaFingerprints: SchemaFingerprint[] = logTypes.map((lt) => ({
    logTypeId: lt.id,
    logTypeName: lt.name,
    fieldCount: lt.fields.length,
    fieldHash: hashFields(lt.fields),
  }));

  // Snapshot analytics rules
  const analyticRules: AnalyticRuleSnapshot[] = [];
  if (isRepoReady() && solutionPath) {
    const solName = solutionPath.replace(/^Solutions\//, '');
    // Try both naming conventions
    for (const dirName of ['Analytic Rules', 'Analytics Rules', 'AnalyticRules']) {
      const ruleFiles = listSolutionFiles(solName, dirName);
      for (const rf of ruleFiles) {
        if (!rf.name.endsWith('.yaml') && !rf.name.endsWith('.yml')) continue;
        const sha = getFileHash(rf.path);
        // Extract rule name and severity from YAML
        const content = readRepoFile(rf.path) || '';
        const ruleName = content.match(/^name:\s*(.+)/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '') || rf.name;
        const severity = content.match(/^severity:\s*(.+)/m)?.[1]?.trim() || 'Unknown';
        const fieldCount = content.match(/^query:/m) ? (content.match(/\b\w+\b/g) || []).length : 0;
        analyticRules.push({ fileName: rf.name, sha, ruleName, severity, fieldCount });
      }
      if (ruleFiles.length > 0) break; // Found the right directory name
    }
  }

  const snapshot: BuildSnapshot = {
    packName,
    solutionName,
    buildTime: Date.now(),
    solutionPath: solutionPath || `Solutions/${solutionName}`,
    gitCommit,
    connectorFiles,
    schemaFingerprints,
    analyticRules,
    totalFields: logTypes.reduce((sum, lt) => sum + lt.fields.length, 0),
  };

  // Persist
  const snapshots = readSnapshots();
  snapshots[packName] = snapshot;
  writeSnapshots(snapshots);

  return snapshot;
}

// Find the Solutions/ path for a vendor name.
// Uses local repo first, falls back to dynamic registry, then GitHub API.
async function findSolutionPath(solutionName: string): Promise<string | null> {
  // Check local repo first (fast filesystem scan)
  if (isRepoReady()) {
    const solDir = getSolutionsDir();
    // Exact match
    if (fs.existsSync(path.join(solDir, solutionName))) {
      return `Solutions/${solutionName}`;
    }
    // Fuzzy match
    const lower = solutionName.toLowerCase().replace(/[^a-z0-9]/g, '');
    try {
      const entries = fs.readdirSync(solDir, { withFileTypes: true });
      for (const entry of entries) {
        if (!entry.isDirectory()) continue;
        const entryLower = entry.name.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (entryLower === lower || entryLower.includes(lower) || lower.includes(entryLower)) {
          return `Solutions/${entry.name}`;
        }
      }
    } catch { /* skip */ }
  }

  // Check dynamic registry
  const dynEntry = lookupDynamicEntry(solutionName);
  if (dynEntry?.solutionPath) return dynEntry.solutionPath;

  // Fallback to GitHub API
  try {
    const encodedName = encodeURIComponent(solutionName);
    const response = await githubGet(`/repos/${SENTINEL_REPO}/contents/Solutions/${encodedName}`);
    const contents = JSON.parse(response);
    if (Array.isArray(contents)) return `Solutions/${solutionName}`;
  } catch { /* not found */ }

  return null;
}

// Fetch Data Connector file metadata.
// Uses local repo when available, falls back to GitHub API.
async function fetchConnectorFiles(solutionPath: string): Promise<GitHubContent[]> {
  if (isRepoReady()) {
    const solName = solutionPath.replace(/^Solutions\//, '');
    const localFiles = listConnectorFiles(solName);
    return localFiles.map((f) => ({
      name: f.name,
      path: f.path,
      type: 'file',
      size: f.size,
      sha: getFileHash(f.path),
    }));
  }

  // Fallback to GitHub API
  const dirNames = ['Data%20Connectors', 'DataConnectors'];
  for (const dirName of dirNames) {
    try {
      const response = await githubGet(`/repos/${SENTINEL_REPO}/contents/${solutionPath}/${dirName}`);
      const contents: GitHubContent[] = JSON.parse(response);
      return contents.filter((f) => f.type === 'file' && f.name.endsWith('.json'));
    } catch { continue; }
  }
  return [];
}

// ---------------------------------------------------------------------------
// Change Detection
// ---------------------------------------------------------------------------

let detectionState: ChangeDetectionState = {
  status: 'idle',
  alerts: [],
  lastCheckTime: 0,
  errorMessage: '',
};

function broadcastDetectionStatus(): void {
  const summary = {
    status: detectionState.status,
    alertCount: detectionState.alerts.filter((a) => a.hasChanges).length,
    criticalCount: detectionState.alerts.reduce((s, a) => s + a.criticalCount, 0),
    warningCount: detectionState.alerts.reduce((s, a) => s + a.warningCount, 0),
    lastCheckTime: detectionState.lastCheckTime,
  };
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) {
      win.webContents.send('changes:status', summary);
    }
  }
}

// Compare a single pack's snapshot against current GitHub state
async function checkPackChanges(snapshot: BuildSnapshot): Promise<ChangeAlert> {
  const changes: ChangeDetail[] = [];
  const checkTime = Date.now();

  // 1. Check connector files for SHA changes
  let currentFiles: GitHubContent[] = [];
  try {
    currentFiles = await fetchConnectorFiles(snapshot.solutionPath);
  } catch {
    // Can't reach GitHub -- skip file-level check
  }

  if (currentFiles.length > 0) {
    const snapshotFileMap = new Map(
      snapshot.connectorFiles.map((f) => [f.fileName, f])
    );
    const currentFileMap = new Map(
      currentFiles.map((f) => [f.name, f])
    );

    // New files
    for (const [name, file] of currentFileMap) {
      if (!snapshotFileMap.has(name)) {
        changes.push({
          category: 'new_connector',
          severity: 'warning',
          description: `New Data Connector file added: ${name}`,
          fileName: name,
        });
      }
    }

    // Modified files (SHA mismatch)
    for (const [name, snapshotFile] of snapshotFileMap) {
      const current = currentFileMap.get(name);
      if (!current) {
        changes.push({
          category: 'removed_connector',
          severity: 'warning',
          description: `Data Connector file removed: ${name}`,
          fileName: name,
        });
      } else if (current.sha && snapshotFile.sha && current.sha !== snapshotFile.sha) {
        changes.push({
          category: 'modified_connector',
          severity: 'critical',
          description: `Data Connector file modified: ${name}`,
          fileName: name,
          oldValue: snapshotFile.sha.slice(0, 8),
          newValue: current.sha.slice(0, 8),
        });
      }
    }
  }

  // 2. Check schema changes by re-parsing current connector files
  if (changes.some((c) => c.category === 'modified_connector' || c.category === 'new_connector')) {
    // Re-fetch and parse schemas from changed/new files
    const currentSchemas = await fetchCurrentSchemas(snapshot.solutionPath);

    if (currentSchemas.length > 0) {
      const snapshotFpMap = new Map(
        snapshot.schemaFingerprints.map((fp) => [fp.logTypeId, fp])
      );

      for (const current of currentSchemas) {
        const snapshotFp = snapshotFpMap.get(current.logTypeId);

        if (!snapshotFp) {
          changes.push({
            category: 'new_log_type',
            severity: 'critical',
            description: `New log type added: ${current.logTypeName} (${current.fieldCount} fields)`,
            logTypeName: current.logTypeName,
            newValue: current.fieldCount,
          });
        } else {
          // Check field hash
          if (snapshotFp.fieldHash !== current.fieldHash) {
            changes.push({
              category: 'schema_change',
              severity: 'critical',
              description: `Schema changed for ${current.logTypeName}: field definitions differ from pack build`,
              logTypeName: current.logTypeName,
              oldValue: snapshotFp.fieldHash,
              newValue: current.fieldHash,
            });
          }
          // Check field count
          if (snapshotFp.fieldCount !== current.fieldCount) {
            changes.push({
              category: 'field_count_change',
              severity: 'warning',
              description: `Field count changed for ${current.logTypeName}: ${snapshotFp.fieldCount} -> ${current.fieldCount}`,
              logTypeName: current.logTypeName,
              oldValue: snapshotFp.fieldCount,
              newValue: current.fieldCount,
            });
          }
        }
      }

      // Check for removed log types
      const currentIds = new Set(currentSchemas.map((s) => s.logTypeId));
      for (const [id, fp] of snapshotFpMap) {
        if (!currentIds.has(id)) {
          changes.push({
            category: 'removed_log_type',
            severity: 'warning',
            description: `Log type removed: ${fp.logTypeName}`,
            logTypeName: fp.logTypeName,
          });
        }
      }
    }
  }

  // 3. Check analytics rule changes
  if (snapshot.analyticRules && snapshot.analyticRules.length > 0 && isRepoReady()) {
    const solName = snapshot.solutionPath.replace(/^Solutions\//, '');
    let currentRuleFiles: Array<{ name: string; path: string; size: number }> = [];
    for (const dirName of ['Analytic Rules', 'Analytics Rules', 'AnalyticRules']) {
      currentRuleFiles = listSolutionFiles(solName, dirName);
      if (currentRuleFiles.length > 0) break;
    }

    const snapshotRuleMap = new Map(snapshot.analyticRules.map((r) => [r.fileName, r]));
    const currentRuleMap = new Map(
      currentRuleFiles
        .filter((f) => f.name.endsWith('.yaml') || f.name.endsWith('.yml'))
        .map((f) => [f.name, f])
    );

    // New rules
    for (const [name] of currentRuleMap) {
      if (!snapshotRuleMap.has(name)) {
        changes.push({
          category: 'new_analytic_rule',
          severity: 'warning',
          description: `New analytics rule added: ${name}`,
          fileName: name,
        });
      }
    }

    // Modified rules (SHA mismatch)
    for (const [name, snapshotRule] of snapshotRuleMap) {
      const current = currentRuleMap.get(name);
      if (!current) {
        changes.push({
          category: 'removed_analytic_rule',
          severity: 'warning',
          description: `Analytics rule removed: ${snapshotRule.ruleName}`,
          fileName: name,
        });
      } else {
        const currentSha = getFileHash(current.path);
        if (currentSha && snapshotRule.sha && currentSha !== snapshotRule.sha) {
          changes.push({
            category: 'modified_analytic_rule',
            severity: 'critical',
            description: `Analytics rule modified: ${snapshotRule.ruleName} -- may reference new fields or changed query logic`,
            fileName: name,
          });
        }
      }
    }
  }

  return {
    packName: snapshot.packName,
    solutionName: snapshot.solutionName,
    solutionPath: snapshot.solutionPath,
    buildTime: snapshot.buildTime,
    checkTime,
    hasChanges: changes.length > 0,
    changes,
    totalChanges: changes.length,
    criticalCount: changes.filter((c) => c.severity === 'critical').length,
    warningCount: changes.filter((c) => c.severity === 'warning').length,
    infoCount: changes.filter((c) => c.severity === 'info').length,
  };
}

// Fetch and fingerprint current schemas for a solution.
// Uses local repo when available for zero API calls.
async function fetchCurrentSchemas(solutionPath: string): Promise<SchemaFingerprint[]> {
  const fingerprints: SchemaFingerprint[] = [];

  if (isRepoReady()) {
    // Read directly from local clone -- no API calls
    const solName = solutionPath.replace(/^Solutions\//, '');
    const files = listConnectorFiles(solName);
    for (const file of files.slice(0, 20)) {
      const parsed = readConnectorJson(file.path);
      if (parsed) {
        const logTypes = extractLogTypesForFingerprint(parsed);
        for (const lt of logTypes) {
          if (!fingerprints.some((fp) => fp.logTypeId === lt.logTypeId)) {
            fingerprints.push(lt);
          }
        }
      }
    }
  } else {
    // Fallback to GitHub API
    const files = await fetchConnectorFiles(solutionPath);
    for (const file of files.slice(0, 10)) {
      try {
        const content = await rawGet(file.path);
        const parsed = JSON.parse(content);
        const logTypes = extractLogTypesForFingerprint(parsed);
        for (const lt of logTypes) {
          if (!fingerprints.some((fp) => fp.logTypeId === lt.logTypeId)) {
            fingerprints.push(lt);
          }
        }
      } catch { /* skip */ }
    }
  }

  return fingerprints;
}

// Lightweight schema extraction just for fingerprinting
function extractLogTypesForFingerprint(json: Record<string, unknown>): SchemaFingerprint[] {
  const results: SchemaFingerprint[] = [];

  if (Array.isArray(json.tables)) {
    for (const table of json.tables) {
      const t = table as Record<string, unknown>;
      if (!t.name) continue;
      const columns = Array.isArray(t.columns) ? t.columns as Array<Record<string, string>> : [];
      const fields = columns.filter((c) => c.name).map((c) => ({
        name: c.name || c.columnName || '',
        type: (c.type || c.columnType || 'string').toLowerCase(),
      }));
      results.push({
        logTypeId: String(t.name).replace(/[^a-zA-Z0-9_]/g, '_'),
        logTypeName: String(t.name),
        fieldCount: fields.length,
        fieldHash: hashFields(fields),
      });
    }
  }

  if (Array.isArray(json.resources)) {
    for (const resource of json.resources) {
      const r = resource as Record<string, unknown>;
      const props = r.properties as Record<string, unknown> | undefined;
      if (!props?.streamDeclarations) continue;
      const streams = props.streamDeclarations as Record<string, { columns?: Array<Record<string, string>> }>;
      for (const [streamName, streamDef] of Object.entries(streams)) {
        if (!Array.isArray(streamDef.columns)) continue;
        const tableName = streamName.replace(/^Custom-/, '');
        const fields = streamDef.columns.filter((c) => c.name).map((c) => ({
          name: c.name, type: (c.type || 'string').toLowerCase(),
        }));
        if (!results.some((r) => r.logTypeId === tableName.replace(/[^a-zA-Z0-9_]/g, '_'))) {
          results.push({
            logTypeId: tableName.replace(/[^a-zA-Z0-9_]/g, '_'),
            logTypeName: tableName,
            fieldCount: fields.length,
            fieldHash: hashFields(fields),
          });
        }
      }
    }
  }

  return results;
}

// Run change detection for all packs with snapshots.
// Processes in series with delays to respect rate limits.
export async function runChangeDetection(): Promise<ChangeAlert[]> {
  const snapshots = readSnapshots();
  const packNames = Object.keys(snapshots);

  if (packNames.length === 0) {
    detectionState = { status: 'done', alerts: [], lastCheckTime: Date.now(), errorMessage: '' };
    broadcastDetectionStatus();
    return [];
  }

  detectionState = {
    status: 'checking',
    alerts: [],
    lastCheckTime: 0,
    errorMessage: '',
  };
  broadcastDetectionStatus();

  const alerts: ChangeAlert[] = [];

  for (const packName of packNames) {
    try {
      const alert = await checkPackChanges(snapshots[packName]);
      alerts.push(alert);
    } catch (err) {
      // Create an error alert for this pack
      alerts.push({
        packName,
        solutionName: snapshots[packName].solutionName,
        solutionPath: snapshots[packName].solutionPath,
        buildTime: snapshots[packName].buildTime,
        checkTime: Date.now(),
        hasChanges: false,
        changes: [],
        totalChanges: 0,
        criticalCount: 0,
        warningCount: 0,
        infoCount: 0,
      });
    }

    // Rate limit delay between packs
    if (packNames.indexOf(packName) < packNames.length - 1) {
      await new Promise((resolve) => setTimeout(resolve, 1500));
    }
  }

  writeAlerts(alerts);
  detectionState = {
    status: 'done',
    alerts,
    lastCheckTime: Date.now(),
    errorMessage: '',
  };
  broadcastDetectionStatus();

  return alerts;
}

// Get the diff report for a specific pack: shows exactly what changed
// since the pack was built, including git commit history and file diffs.
export async function getPackDiff(packName: string): Promise<{
  packName: string;
  solutionName: string;
  buildTime: number;
  daysSinceBuild: number;
  buildCommit: string;
  currentCommit: string;
  changes: ChangeDetail[];
  gitLog: GitCommitInfo[];
  fileDiffs: FileDiff[];
  recommendation: string;
} | null> {
  const snapshots = readSnapshots();
  const snapshot = snapshots[packName];
  if (!snapshot) return null;

  const alert = await checkPackChanges(snapshot);
  const daysSinceBuild = Math.floor((Date.now() - snapshot.buildTime) / (1000 * 60 * 60 * 24));
  const currentCommit = await getCurrentCommit();

  // Get git history and file diffs if we have a build commit to compare against
  let gitLog: GitCommitInfo[] = [];
  let fileDiffs: FileDiff[] = [];
  if (snapshot.gitCommit && isRepoReady()) {
    gitLog = await getGitLogForPath(snapshot.solutionPath, snapshot.gitCommit, 30);
    fileDiffs = await getFileDiffSinceCommit(snapshot.solutionPath, snapshot.gitCommit);
  }

  let recommendation = 'No changes detected. Pack is up to date.';
  const hasRuleChanges = alert.changes.some((c) =>
    c.category === 'new_analytic_rule' || c.category === 'modified_analytic_rule' || c.category === 'removed_analytic_rule'
  );
  if (alert.criticalCount > 0) {
    const schemaChanged = alert.changes.some((c) => c.category === 'schema_change' || c.category === 'new_log_type');
    const ruleModified = alert.changes.some((c) => c.category === 'modified_analytic_rule');
    recommendation = 'REBUILD RECOMMENDED: '
      + (schemaChanged ? 'Schema changes detected that may affect data ingestion. ' : '')
      + (ruleModified ? 'Analytics rules have been modified -- field requirements may have changed. ' : '')
      + 'Rebuild the pack to incorporate updates.';
  } else if (alert.warningCount > 0) {
    recommendation = 'REVIEW RECOMMENDED: '
      + (hasRuleChanges ? 'Analytics rules have been added or removed. Re-run rule coverage analysis. ' : '')
      + 'Check if the changes affect your data collection coverage.';
  } else if (gitLog.length > 0) {
    recommendation = `${gitLog.length} commit(s) to this solution since your build, but no schema impact detected. Review if needed.`;
  } else if (daysSinceBuild > 90) {
    recommendation = 'Pack is over 90 days old. Consider rebuilding to pick up any improvements.';
  }

  return {
    packName: snapshot.packName,
    solutionName: snapshot.solutionName,
    buildTime: snapshot.buildTime,
    daysSinceBuild,
    buildCommit: snapshot.gitCommit || '',
    currentCommit,
    changes: alert.changes,
    gitLog,
    fileDiffs,
    recommendation,
  };
}

// ---------------------------------------------------------------------------
// IPC Handlers
// ---------------------------------------------------------------------------

export function registerChangeDetectionHandlers(ipcMain: IpcMain) {
  // Get current detection status + all alerts
  ipcMain.handle('changes:status', async () => {
    return {
      status: detectionState.status,
      lastCheckTime: detectionState.lastCheckTime,
      alerts: detectionState.alerts,
      summary: {
        totalPacks: detectionState.alerts.length,
        packsWithChanges: detectionState.alerts.filter((a) => a.hasChanges).length,
        criticalCount: detectionState.alerts.reduce((s, a) => s + a.criticalCount, 0),
        warningCount: detectionState.alerts.reduce((s, a) => s + a.warningCount, 0),
      },
    };
  });

  // Trigger change detection for all packs
  ipcMain.handle('changes:check', async () => {
    if (detectionState.status === 'checking') {
      return { started: false, reason: 'Check already in progress' };
    }
    // Run in background
    runChangeDetection().catch((err) => {
      detectionState.status = 'error';
      detectionState.errorMessage = err instanceof Error ? err.message : String(err);
      broadcastDetectionStatus();
    });
    return { started: true };
  });

  // Get alerts for a specific pack
  ipcMain.handle('changes:pack-alerts', async (_event, { packName }: { packName: string }) => {
    const cached = readAlerts();
    return cached.find((a) => a.packName === packName) || null;
  });

  // Get full diff for a specific pack (live check, not cached)
  ipcMain.handle('changes:pack-diff', async (_event, { packName }: { packName: string }) => {
    return getPackDiff(packName);
  });

  // Get git log for a solution path since a specific commit
  ipcMain.handle('changes:git-log', async (_event, {
    solutionPath, sinceCommit, maxEntries,
  }: { solutionPath: string; sinceCommit?: string; maxEntries?: number }) => {
    return getGitLogForPath(solutionPath, sinceCommit, maxEntries || 30);
  });

  // Get file-level diffs for a solution since a commit
  ipcMain.handle('changes:file-diffs', async (_event, {
    solutionPath, sinceCommit,
  }: { solutionPath: string; sinceCommit: string }) => {
    return getFileDiffSinceCommit(solutionPath, sinceCommit);
  });

  // Get all snapshots (for UI listing)
  ipcMain.handle('changes:snapshots', async () => {
    return readSnapshots();
  });

  // Delete a snapshot (when a pack is deleted)
  ipcMain.handle('changes:delete-snapshot', async (_event, { packName }: { packName: string }) => {
    const snapshots = readSnapshots();
    delete snapshots[packName];
    writeSnapshots(snapshots);
  });

  // Dismiss/acknowledge changes for a pack
  ipcMain.handle('changes:dismiss', async (_event, { packName }: { packName: string }) => {
    const alerts = readAlerts();
    const idx = alerts.findIndex((a) => a.packName === packName);
    if (idx !== -1) {
      alerts[idx].hasChanges = false;
      alerts[idx].changes = [];
      alerts[idx].totalChanges = 0;
      alerts[idx].criticalCount = 0;
      alerts[idx].warningCount = 0;
      alerts[idx].infoCount = 0;
      writeAlerts(alerts);
      detectionState.alerts = alerts;
      broadcastDetectionStatus();
    }
  });
}
